blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/jepemo/miko-manifest/discussions
    about: Ask questions and get help from the community
  - name: Security Issues
    url: https://github.com/jepemo/miko-manifest/security/policy
    about: Report security vulnerabilities privately
