---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "my-app"
  namespace: "default"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
        - name: "my-app"
          image: "nginx:v1.2.3"
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
