apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                port:
                  type: integer
                name:
                  type: string
              required:
                - host
                - port
                - name
            status:
              type: object
              properties:
                ready:
                  type: boolean
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
