name: Miko-Shell CI

on:
  push:
    branches: [main, develop]
    paths: ['miko-shell.yaml', '.github/workflows/miko-shell-ci.yml']
  pull_request:
    branches: [main, develop]
    paths: ['miko-shell.yaml', '.github/workflows/miko-shell-ci.yml']

env:
  MIKO_SHELL_VERSION: latest

jobs:
  test-with-miko-shell:
    name: Test with Miko-Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install miko-shell
        run: |
          curl -sSL https://raw.githubusercontent.com/jepemo/miko-shell/main/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify miko-shell installation
        run: |
          miko-shell version
          miko-shell run help

      - name: Build container image
        run: |
          miko-shell image build

      - name: Run tests
        run: |
          miko-shell run test

      - name: Run tests with coverage
        run: |
          miko-shell run test-coverage

      - name: Run linting
        run: |
          miko-shell run lint

      - name: Run pre-commit checks
        run: |
          miko-shell run precommit

      - name: Build binary
        run: |
          miko-shell run build dev

      - name: Verify binary
        run: |
          if [ -f miko-manifest ]; then
            echo "✅ Binary built successfully"
            ls -la miko-manifest
          else
            echo "❌ Binary not found"
            exit 1
          fi

  compatibility-check:
    name: Makefile vs Miko-Shell Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-method: [makefile, miko-shell]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go (for Makefile)
        if: matrix.build-method == 'makefile'
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Set up Docker (for Miko-Shell)
        if: matrix.build-method == 'miko-shell'
        uses: docker/setup-buildx-action@v3

      - name: Install miko-shell
        if: matrix.build-method == 'miko-shell'
        run: |
          curl -sSL https://raw.githubusercontent.com/jepemo/miko-shell/main/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests (Makefile)
        if: matrix.build-method == 'makefile'
        run: |
          make deps
          make test

      - name: Run tests (Miko-Shell)
        if: matrix.build-method == 'miko-shell'
        run: |
          miko-shell image build
          miko-shell run test

      - name: Build binary (Makefile)
        if: matrix.build-method == 'makefile'
        run: |
          make build

      - name: Build binary (Miko-Shell)
        if: matrix.build-method == 'miko-shell'
        run: |
          miko-shell run build

      - name: Compare results
        run: |
          if [ -f miko-manifest ]; then
            echo "✅ Binary created successfully with ${{ matrix.build-method }}"
            file miko-manifest
            ls -la miko-manifest
          else
            echo "❌ Binary not created with ${{ matrix.build-method }}"
            exit 1
          fi
